clear;
load gTruth.mat;
load datalayers.mat
layers=data.fastRCNNLayers;
trainingdata= gTruth;

options = trainingOptions('sgdm', ...
      'MiniBatchSize', 1, ...
      'InitialLearnRate', 1e-4, ...
      'MaxEpochs', 10, ...
      'Shuffle','never', ...
      'CheckpointPath', tempdir);

 [frcnn,info] = trainFastRCNNObjectDetector(trainingdata, layers , options, ...
      'NegativeOverlapRange', [0 0.1], ...
      'PositiveOverlapRange', [0.2 1], ...
      'NumRegionsToSample', 128, ...
      'SmallestImageDimension', 600);
  
  save frcnn frcnn;
  


